# Generated by Django 5.2.4 on 2025-07-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral_system", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="invite_code",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
