# Generated by Django 5.2.4 on 2025-07-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral_system", "0002_remove_user_is_active_alter_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userphonecode",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
