# Generated by Django 5.2.4 on 2025-07-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral_system", "0003_alter_userphonecode_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
